machine:
  java:
    version: oraclejdk8
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux
    GRADLE_OPTS: -Xmx512m

dependencies:
  pre:
    - echo y | android update sdk --no-ui --all --filter "tools,platform-tools,android-23,extra-android-support,extra-android-m2repository"
    - echo y | android update sdk --no-ui --all --filter "build-tools-23.0.2"
  cache_directories:
    - ~/.android
  override:
    - ./gradlew dependencies

test:
  override:
    - ./gradlew clean check
