language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-27
    - build-tools-27.0.3

env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

script:
  - ./gradlew clean assembleDebug :launcher:test

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
